name= input('Hey! What is your name? ')
Print('Nice to meet you' + name+'!')
age= input('How old are you?')
print('Woah,'+ age + 'years old?! I was born yesterday.')
feeling= input('How are you doing today?')
print("That is great to hear" + feeling.lower()+"That is wonderful to hear!")